navbar:
  blog_title: Chuck's Blog

  # 导航栏菜单，可自行增减，key 用来关联 languages/*.yml，如不存在关联则显示 key 本身的值；icon 是 css class，可以省略；增加 name 可以强制显示指定名称
  # Navigation bar menu. `key` is used to associate languages/*.yml. If there is no association, the value of `key` itself will be displayed; if `icon` is a css class, it can be omitted; adding `name` can force the display of the specified name
  menu:
    - key: 'home'
      link: '/'
      icon: 'iconfont icon-home-fill'
    - key: 'archive'
      link: '/archives/'
      icon: 'iconfont icon-archive-fill'
    - key: 'category'
      link: '/categories/'
      icon: 'iconfont icon-category-fill'
    - key: 'tag'
      link: '/tags/'
      icon: 'iconfont icon-tags-fill'
    - key: 'about'
      link: '/about/'
      icon: 'iconfont icon-user-fill'
    - key: 'links'
      link: '/links/'
      icon: 'iconfont icon-link-fill'

index:
  slogan:
    enable: true
    text: Keep coding, Keep thinking.

links:
  items:
    - title: 'Onion 洋葱'
      intro: '洋葱的Blog呀！'
      link: 'https://onionnet.work/'
      avatar: 'https://onionnet.work/images/200x200.png'
